In [36]:
import torch

In [37]:
def activation(x):
    return (1/(1+torch.exp(-x)))

In [38]:
#Single Layer Neural Network
torch.manual_seed(8)
features = torch.randn(1,5)
weights=torch.randn_like(features)
bias=torch.randn(1,1)

In [39]:
y=activation(torch.mm(features,weights.view(5,1))+bias)

In [40]:
#Multi Layer Neural Network
torch.manual_seed(7)
features = torch.randn(1,3)
inputs=features.shape[1]
hiddens=2
outputs=1
weights_1=torch.randn(inputs,hiddens)
weights_2=torch.randn(hiddens,outputs)
bias_1=torch.randn(1,hiddens)
bias_2=torch.randn(1,outputs)

In [41]:
h=activation(torch.mm(features,weights_1)+bias_1)
y=activation(torch.mm(h,weights_2)+bias_2)

In [42]:
print(y)

tensor([[0.3171]])


In [43]:
#Numpy to torch and back
import numpy as np
a=np.random.rand(4,3)
a

array([[0.37914582, 0.45235228, 0.27046943],
       [0.24474779, 0.64576751, 0.70314718],
       [0.92283272, 0.45591618, 0.93370401],
       [0.03609707, 0.97492559, 0.67148374]])

In [44]:
b=torch.from_numpy(a)
b

tensor([[0.3791, 0.4524, 0.2705],
        [0.2447, 0.6458, 0.7031],
        [0.9228, 0.4559, 0.9337],
        [0.0361, 0.9749, 0.6715]], dtype=torch.float64)

In [45]:
b.numpy()

array([[0.37914582, 0.45235228, 0.27046943],
       [0.24474779, 0.64576751, 0.70314718],
       [0.92283272, 0.45591618, 0.93370401],
       [0.03609707, 0.97492559, 0.67148374]])

In [46]:
b

tensor([[0.3791, 0.4524, 0.2705],
        [0.2447, 0.6458, 0.7031],
        [0.9228, 0.4559, 0.9337],
        [0.0361, 0.9749, 0.6715]], dtype=torch.float64)

In [47]:
b.mul_(2)

tensor([[0.7583, 0.9047, 0.5409],
        [0.4895, 1.2915, 1.4063],
        [1.8457, 0.9118, 1.8674],
        [0.0722, 1.9499, 1.3430]], dtype=torch.float64)

In [48]:
b*2

tensor([[1.5166, 1.8094, 1.0819],
        [0.9790, 2.5831, 2.8126],
        [3.6913, 1.8237, 3.7348],
        [0.1444, 3.8997, 2.6859]], dtype=torch.float64)

In [49]:
a

array([[0.75829165, 0.90470457, 0.54093885],
       [0.48949559, 1.29153502, 1.40629436],
       [1.84566543, 0.91183237, 1.86740802],
       [0.07219413, 1.94985119, 1.34296748]])

In [50]:
b

tensor([[0.7583, 0.9047, 0.5409],
        [0.4895, 1.2915, 1.4063],
        [1.8457, 0.9118, 1.8674],
        [0.0722, 1.9499, 1.3430]], dtype=torch.float64)